#! /bin/sh

#programs which need to be run on startup:
sxhkd &
redshift &
compton &
dunst &

#Setting the wallpaper here:
feh --bg-scale ~/Pictures/Wallpapers/groot-i-am-root-qhd-1920x1080.jpg

#bspc monitor HDMI-0 -d I II III IV V 
#bspc monitor HDMI-1 -d VI VII VIII IX X

#Setting up the monitors with their labels:
bspc monitor HDMI-0 -d "1. " "2. " "3. " "4. " "5. " 
bspc monitor HDMI-1 -d "6. " "7. " "8. " "9. " "10. "

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

#Rules for coloring borders:
bspc config focused_border_color "#8EC07C"
bspc config normal_border_color "#83A598" 
bspc config active_border_color "#FABD2F"

#Rules for specific applications:
bspc rule -a Google-chrome desktop='^6' state=fullscreen
bspc rule -a Slack desktop='^8'

#Arbitrary startup applications:
google-chrome-stable
slack

#Launching polybar on startup:
$HOME/.config/polybar/launch.sh
