#! /bin/sh

#Essential startup applications:
sxhkd &
compton &
polybar bar &

#Setting wallpaper through feh:
feh --bg-scale ~/Pictures/Wallpapers/current_wallpaper.jpg

#Default monitor configuration:
#bspc monitor -d I II III IV V VI VII VIII IX X

#Current monitor configuration:
bspc monitor -d "1 " "2 " "3 " "4 " "5 " "6 " "7 " "8 " "9 " "10 "

#Options:
bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

#Rules for coloring borders:
bspc config focused_border_color "#8EC07C"
bspc config normal_border_color "#83A598" 
bspc config active_border_color "#FABD2F"

#Rules for specific applications:
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Slack desktop='^9'
